name: Screenshot
description: Snap a JPG of the provided site

inputs:
  source:
    description: "The site handle to screenshot"
    required: true
  command:
    description: "The screenshot.py command to run"
    required: true

runs:
  using: "composite"
  steps:
    - id: install-extras
      name: Install Ubuntu codecs and extras
      run: |
        sudo apt update
        sudo apt install xvfb
      shell: bash

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run playwright install --with-deps chromium
      shell: bash

    - id: install-brave
      name: Install Brave browser
      run: |
        sudo apt install apt-transport-https curl
        sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
        sudo apt update
        sudo apt install brave-browser
        which brave-browser
      shell: bash

    - id: headless
      name: Take headless screenshot
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run python -m newshomepages.screenshot headless
      shell: bash

    - id: headful
      name: Take headful screenshot
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run python -m newshomepages.screenshot headful
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: _dist
        if-no-files-found: error
