name: Screenshot
description: Snap a JPG of the provided site

inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  options:
    description: “Options on the screenshot command”
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run playwright install --with-deps chromium
      shell: bash

    - id: shoot
      name: Take screenshot
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pipenv run python -m newshomepages.screenshot ${{ inputs.source }} -o _dist ${{ inputs.options }}
      shell: bash
      env:
        DEBUG: 'pw:api'
        CHROME_IPC_LOGGING: 1

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: _dist
        if-no-files-found: error
