name: Screenshot
description: Snap a JPG of the provided site

inputs:
  source:
    description: “The site handle to screenshot”
    required: true
  command:
    description: "The screenshot.py command to run"
    required: true

runs:
  using: "composite"
  steps:
    - id: install-extras
      name: Install Ubuntu codecs and extras
      run: |
        sudo apt-get update
        sudo apt-get install xorg openbox xinit lightdm
        sudo systemctl start lightdm
#        sudo apt install -y ubuntu-restricted-extras ffmpeg libavcodec-extra xvfb libxcb-dri3-dev
      shell: bash

    - id: cache-playwright
      name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers

    - id: install-playwright
      name: Install Playwright dependencies
      run: pipenv run playwright install --with-deps chromium
      shell: bash

    - id: shoot
      name: Take screenshot
      run: xvfb-run pipenv run python -m newshomepages.screenshot ${{ inputs.command }} ${{ inputs.source }} -o _dist
      shell: bash

    - id: save
      name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: _dist
        if-no-files-found: error
