# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: newshomepages/extensions/
    -   id: end-of-file-fixer
        exclude: newshomepages/extensions/
    -   id: check-yaml
        exclude: newshomepages/extensions/
    -   id: check-added-large-files
        args: ['--maxkb=10000']
    -   id: check-byte-order-marker
        exclude: newshomepages/extensions
    -   id: check-case-conflict
        exclude: newshomepages/extensions/
    -   id: check-json
        exclude: newshomepages/extensions/
    -   id: mixed-line-ending
        exclude: newshomepages/extensions/

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: newshomepages/extensions/
    -   id: ruff-format
        exclude: newshomepages/extensions/
