name: Docs
description: Update templated documentation pages

runs:
  using: "composite"
  steps:
    - id: install
      name: Install
      uses: ./.github/actions/install

    - id: latest-screenshots
      name: Update latest screenshots
      run: pipenv run python -m newshomepages.docs latest-screenshots;
      shell: bash

    - id: git-add-archive
      name: Git add latest files
      run: pipenv run python -m newshomepages.extract latest-files
      shell: bash

    - id: accessibility-ranking
      name: Update accessibility ranking
      run: pipenv run python -m newshomepages.docs accessibility-ranking;
      shell: bash

    - id: performance-ranking
      name: Update performance ranking
      run: pipenv run python -m newshomepages.docs performance-ranking;
      shell: bash

    - id: drudge-ranking
      name: Update Drudge ranking
      run: pipenv run python -m newshomepages.docs drudge-ranking;
      shell: bash

    - id: source-list
      name: Update source list
      run: pipenv run python -m newshomepages.docs source-list;
      shell: bash

    - id: bundle-list
      name: Update bundle list
      run: pipenv run python -m newshomepages.docs bundle-list;
      shell: bash

    - id: country-list
      name: Update country list
      run: pipenv run python -m newshomepages.docs country-list;
      shell: bash

    - id: language-list
      name: Update language list
      run: pipenv run python -m newshomepages.docs language-list;
      shell: bash

    - id: site-detail
      name: Update site detail
      run: pipenv run python -m newshomepages.docs site-detail;
      shell: bash

    - id: site-detail-lighthouse-analysis-chart
      name: Update site detail lighthouse analysis
      run: pipenv run python -m newshomepages.docs site-detail-lighthouse-analysis-chart;
      shell: bash

    - id: site-detail-screenshot-chart
      name: Update site detail screenshot chart
      run: pipenv run python -m newshomepages.docs site-detail-screenshot-chart;
      shell: bash

    - id: site-detail-hyperlink-chart
      name: Update site detail hyperlink chart
      run: pipenv run python -m newshomepages.docs site-detail-hyperlink-chart;
      shell: bash

    - id: site-detail-accessibility-chart
      name: Update site detail accessibility chart
      run: pipenv run python -m newshomepages.docs site-detail-accessibility-chart;
      shell: bash

    - id: site-detail-lighthouse-chart
      name: Update site detail lighthouse chart
      run: pipenv run python -m newshomepages.docs site-detail-lighthouse-chart;
      shell: bash

    - id: bundle-detail
      name: Update bundle detail
      run: pipenv run python -m newshomepages.docs bundle-detail;
      shell: bash

    - id: country-detail
      name: Update country detail
      run: pipenv run python -m newshomepages.docs country-detail;
      shell: bash

    - id: language-detail
      name: Update language detail
      run: pipenv run python -m newshomepages.docs language-detail;
      shell: bash

    - id: configure-github
      name: Configure GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config pull.rebase false
      shell: bash

    - id: git-add
      name: Git add
      run:  git add ./
      shell: bash

    - id: git-commit
      name: Git commit
      run: git commit -m "Update docs" --author="palewire <palewire@users.noreply.github.com>" && git push || true
      shell: bash

    - id: git-pull
      name: Git pull
      run: git pull origin $GITHUB_REF
      shell: bash

    - id: git-push
      name: Git push
      run: git push || true
      shell: bash
