name: Docs
description: Update templated documentation pages

runs:
  using: "composite"
  steps:
    - id: latest-screenshots
      name: Update latest screenshots
      run: pipenv run python -m newshomepages.docs latest-screenshots;
      shell: bash

    - id: source-list
      name: Update source list
      run: pipenv run python -m newshomepages.docs source-list;
      shell: bash

    - id: site-detail
      name: Update site detail
      run: pipenv run python -m newshomepages.docs site-detail;
      shell: bash

    - id: commit
      name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config pull.rebase false
        git status
        git pull origin $GITHUB_REF
        git add ./docs/latest.md
        git add ./docs/sources.md
        git add ./docs/sites
        git commit -m "Update docs" --author="palewire <palewire@users.noreply.github.com>" && git push || true
      shell: bash
