name: Twitter
description: Post the mosaic to Twitter

inputs:
  consumer-key:
    required: true
  consumer-secret:
    required: true
  access-token-key:
    required: true
  access-token-secret:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: mosaics

    - id: tweet
      name: Tweet
      run: pipenv run python -m newshomepages.tweet mosaic -i ./mosaics
      shell: bash
      env:
        TWITTER_CONSUMER_KEY: ${{ inputs.consumer-key }}
        TWITTER_CONSUMER_SECRET: ${{ inputs.consumer-secret }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ inputs.access-token-key }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ inputs.access-token-secret }}
