name: Install
description: Install all of the common Python dependencies

runs:
  using: "composite"
  steps:
    - id: install-pipenv
      name: Install pipenv
      run: pipx install pipenv
      shell: bash

    - id: install-python
      name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
        cache: "pipenv"

    - id: install-python-dependencies
      name: Install Python dependencies
      run: pipenv install --dev
      shell: bash
