name: Commit
description: Save the latest screenshots to the repository

runs:
  using: "composite"
  steps:
    - id: install
      name: Install Python dependencies
      uses: ./.github/actions/install

    - id: configure-github
      name: Configure GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config pull.rebase false
      shell: bash

    - name: Git status
      run: git status
      shell: bash

    - id: git-pull
      name: Git pull
      run: git pull origin $GITHUB_REF
      shell: bash

    - name: Git status
      run: git status
      shell: bash

    - uses: actions/download-artifact@v3
      with:
        name: screenshots
        path: ./latest-screenshots

    - uses: actions/download-artifact@v3
      with:
        name: archive
        path: ./newshomepages/sources/latest/

    - name: Git status
      run: git status
      shell: bash

    - id: git-add
      name: Git add latest images
      run: git add ./latest-screenshots/*.jpg
      shell: bash

    - id: git-commit
      name: Git commit
      run: git commit -m "Latest screenshots" --author="palewire <palewire@users.noreply.github.com>" && git push || true
      shell: bash

    - id: git-add-archive
      name: Git add latest files
      run: |
        pipenv run python -m newshomepages.extract latest-files
        git add ./newshomepages/sources/latest/*.json
        git add ./extracts/csv/latest-files.csv
      shell: bash

    - id: git-commit-archive
      name: Git commit
      run: git commit -m "Latest archive.org urls" --author="palewire <palewire@users.noreply.github.com>" && git push || true
      shell: bash
