name: "Archive: Technology"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  archive-bundle:
    uses: palewire/newshomepages/.github/workflows/reusable-archive-bundle-workflow.yml@main
    with:
      bundle: tech
