name: "Archive: San Francisco Bay Area"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-bundle-workflow.yml@main
    with:
      bundle: bay-area
    secrets: inherit
