name: "Archive: Baltimore Sun"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10,16,22 * * *"

jobs:
  archive-site:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-and-slack-workflow.yml@main
    with:
      handle: baltimoresun
      webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_BALTIMORESUN }}
    secrets: inherit
