name: "Archive: U.K. national"

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 9 * * *"

jobs:
  archive-bundle:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-bundle-workflow.yml@main
    with:
      bundle: uk-national
    secrets: inherit
