name: Extract
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  extract:
    name: Extract
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: extract
        name: Extract
        uses: ./.github/actions/extract
        with:
          access-key: ${{ secrets.IA_ACCESS_KEY }}
          secret-key: ${{ secrets.IA_SECRET_KEY }}
          collection: ${{ secrets.IA_COLLECTION }}
