name: "Build website"
on:
  push:
    on: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  docs:
    name: Update docs
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: docs
        name: Docs
        uses: ./.github/actions/docs

  rss:
    name: Update RSS
    runs-on: ubuntu-latest
    needs: [docs]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: rss
        name: RSS
        uses: ./.github/actions/rss

  deploy:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    needs: [docs,rss]
    steps:
    - uses: actions/checkout@v2

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - uses: actions/upload-artifact@v1
      with:
        name: documentation-html
        path: docs/_build/html/

    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
        source_dir: docs/_build/html/
        destination_dir: news-homepages
