name: "Update website"

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Archive a single site
    types:
      - completed
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: docs
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: update-docs
        name: Update docs
        uses: ./.github/actions/site
        with:
          api-key: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
          api-secret-access-key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
