name: "Update website"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

concurrency:
  group: docs
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: update-docs
        name: Update docs
        uses: ./.github/actions/docs

      - id: update-rss
        name: Update RSS
        uses: ./.github/actions/rss

      - id: build-docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - id: upload-docs
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
          source_dir: .docs/_build/html/
          destination_dir: news-homepages
