name: Testing
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-python:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: lint
        name: Lint
        run: pipenv run flake8 ./

  test-python:
    name: Test Python code
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install Python and dependencies
        uses: ./.github/actions/install

      - id: install-xvfb
        name: Install xvfb
        run: sudo apt install -y xvfb
        shell: bash

      - id: test
        name: Run tests
        run: |
            Xvfb $DISPLAY -screen 0 1920x1080x24 &
            pipenv run pytest tests
        env:
          DISPLAY: :99

  static-type-check:
    name: Static type check
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: install
        name: Install
        uses: ./.github/actions/install

      - id: mypy
        name: mypy
        run: pipenv run mypy ./
